### ISSUE TITLE
Some details about finetuning

### ISSUE THREAD

**Issue by vealocia** [Computer-Vision-in-the-Wild/Elevater_Toolkit_IC#1]
Hi authors, thanks for your great work and useful toolkit! Just as the title, would you like to share some of settings in your experiments? Such as:
1. How long does it take to **finetune** one pre-trained model like CLIP-ViT-B/16 on **20** classification datasets?
2. For experiments on a single datasets (e.g., cifar100), how many gpus did you use? 

(Simply excute ```run.sh``` only involves one gpu and requires long training time under my case)
Looking forward to your reply :)

**Comment by junha1125** [comment]
Dear @vealocia,
Did you find the answers to your questions? If yes, could you share them?
Best wishes,
