### ISSUE TITLE
EvalAI taking too long

### ISSUE THREAD

**Issue by nibtehaz** [Computer-Vision-in-the-Wild/Elevater_Toolkit_IC#15]
Hi, first of all thank you for developing such a wonderful benchmark for zero-shot learning assessment.

I have submit some predictions to EvalAI, and it has been running for more than 1 hour. Is the evaluation system working properly?

Thanks.

**Comment by haotian-liu** [comment]
The eval server is up and running now. Your submission is evaluated, and please let us know if you experiment issues with future submissions. Thanks.

**Comment by nibtehaz** [comment]
Thank you for solving the issue so quickly.

**Comment by nibtehaz** [comment]
Hi @haotian-liu , I have another question.  Are the test accuracy reported at the end of the log files same as the value obtained from EvalAI? Thank you.

**Comment by haotian-liu** [comment]
They should be the same.

**Comment by nibtehaz** [comment]
Thanks for the clarification.
