### ISSUE TITLE
Recommendation with Vision Projection and Text Projection for Zero-shot learning

### ISSUE THREAD

**Issue by nibtehaz** [Computer-Vision-in-the-Wild/Elevater_Toolkit_IC#16]
Hi, I wish to evaluate zero shot learning on a new model. Taking the clip_swin.py as example, there are two parameters which are kind of uninitialized due to being created from torch.empty. trunc_normal has been applied later on, but for the same seed I am receiving drastically different accuracy scores.

What do you recommend in my situation, the model I am trying is maxvit_tiny from torchvision pretrained weight and pretrained vitb32_CLIP. 

Thank you for creating this wonderful benchmark.

**Comment by haotian-liu** [comment]
Hi @nibtehaz 

I do not get where the randomness comes from for zero-shot prediction setting. Can you elaborate?

**Comment by nibtehaz** [comment]
Hi @haotian-liu 

I think that randomness is coming from here (code from Elevater_Toolkit_IC/vision_benchmark/models/clip_swin.py)

```
self.vision_projection = nn.Parameter(
            torch.empty(width, embed_dim)
        )

trunc_normal_(self.vision_projection, std=.02)
```

torch.empty would hold garbage values right ? So probably the trunc_normal_ is not helping much.

**Comment by nibtehaz** [comment]
Suppose we set the seed somewhere and change torch.empty to torch.rand or np.random.randn, the results will be reproducible.

**Comment by haotian-liu** [comment]
For zero-shot prediction, they will be initialized with the language embeddings of the class name + prompts -- so they will be deterministic ([here](https://github.com/Computer-Vision-in-the-Wild/Elevater_Toolkit_IC/blob/main/vision_benchmark/evaluation/feature.py#L432), and see our paper or CLIP paper for more details.

**Comment by nibtehaz** [comment]
Alright then, thanks for the insight, need to figure out why I have so much random fluctuations.
