### ISSUE TITLE
An error when running mocoV3

### ISSUE THREAD

**Issue by jiayujack** [Computer-Vision-in-the-Wild/Elevater_Toolkit_IC#2]
I tried to run MoCoV3 on your Evaluation Toolkit, but met a problem in loading the model.

  I only changed parameter model_cfg from vitb16_CLIP to mocov3_vitb16 as suggested and didn't make any other changes, but it seems that MoCo model cannot be correctly loaded.

  Is MoCov3 supported in the current version of Evaluation Toolkit. If so, what should I do to get it correct?

**Comment by haotian-liu** [comment]
Hi, thank you for your interest in our benchmark and toolkit.  Please set `init_head_with_text_encoder=False`, since MoCov3 does not have a language encoder.  If it does not work yet, please share the error message you are getting so that we can better understand the issue.  Thanks!

**Comment by jiayujack** [comment]
thanks a lot, it works now
