### ISSUE TITLE
efficiency score on parameters-efficiency track

### ISSUE THREAD

**Issue by lynlynlyn** [Computer-Vision-in-the-Wild/Elevater_Toolkit_IC#5]
Hi, thanks for your great benchmark.

I wonder how the "**Efficiency**" score is calculated. Is the challenge ranked based on this scores?

**Comment by haotian-liu** [comment]
Thank you for your interest in our benchmark.  We have updated the description of the formula used for accuracy-efficiency metric on [eval.ai](https://eval.ai/web/challenges/challenge-page/1832/evaluation):

```
score * np.exp(-np.log10(n_trainable / 1e8 + 1))
```

We'll also include this clarification in the updated version of our paper.  Thanks.

**Comment by lynlynlyn** [comment]
thanks
