### ISSUE TITLE
AttributeError when custom model does not have a 'visual' branch

### ISSUE THREAD

**Issue by ChenDelong1999** [Computer-Vision-in-the-Wild/Elevater_Toolkit_IC#6]
It seems that the following line of code tries to load the visual branch of the model. 

https://github.com/Computer-Vision-in-the-Wild/Elevater_Toolkit_IC/blob/9d3962074e5a0e02700c87d33d4714aec15b6a28/vision_benchmark/evaluation/feature.py#L326

However, when the model (e.g., a custom model) does not have a visual branch, an AttributeError would be raised.

This problem can be solved by modifying it into:

```python
visual_backbone = model.visual if hasattr(model, 'visual') else model
```

**Comment by haotian-liu** [comment]
Thank you for the information!  It's fixed now.
